window.__envs = {
NEXT_PUBLIC_AD_BANNER_PROVIDER: "none",
NEXT_PUBLIC_NETWORK_CURRENCY_IMAGE_URL: "https://assets.coingecko.com/coins/images/1/standard/bitcoin.png",
NEXT_PUBLIC_NETWORK_ICON_DARK: "http://blockscout-rpc-adaptor:8888/images/light_icon.png",
NEXT_PUBLIC_NAVIGATION_HIDDEN_LINKS: "['eth_rpc_api','rpc_api']",
NEXT_PUBLIC_APP_PROTOCOL: "https",
NEXT_PUBLIC_VISUALIZE_API_HOST: "https://svmscan.io/",
NEXT_PUBLIC_NETWORK_CURRENCY_DECIMALS: "18",
NEXT_PUBLIC_STATS_API_HOST: "https://stats.svmscan.io",
NEXT_PUBLIC_HOMEPAGE_TX_ICON: "https://svmscan.io/blockscout-rpc-adaptor/images/transactions2.svg",
NEXT_PUBLIC_GIT_COMMIT_SHA: "",
NEXT_PUBLIC_WEB3_WALLETS: "['metamask']",
NEXT_PUBLIC_NETWORK_LOGO_DARK: "http://blockscout-rpc-adaptor:8888/images/icon.svg",
NEXT_PUBLIC_API_WEBSOCKET_PROTOCOL: "wss",
NEXT_PUBLIC_NETWORK_CURRENCY_NAME: "BTC",
NEXT_PUBLIC_NETWORK_CURRENCY_SYMBOL: "BTC",
NEXT_PUBLIC_HOMEPAGE_CHARTS: "['daily_txs','coin_price']",
NEXT_PUBLIC_API_HOST: "svmscan.io",
NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID: "fb2816366c39cb48445d32d0e522f0cc",
NEXT_PUBLIC_OG_DESCRIPTION: "SatoshiVM Alpha Mainnet explorer",
NEXT_PUBLIC_AD_TEXT_PROVIDER: "none",
NEXT_PUBLIC_APP_HOST: "svmscan.io",
NEXT_PUBLIC_API_BASE_PATH: "/",
NEXT_PUBLIC_API_SPEC_URL: "https://raw.githubusercontent.com/blockscout/blockscout-api-v2-swagger/main/swagger.yaml",
NEXT_PUBLIC_API_PORT: "443",
NEXT_PUBLIC_GIT_TAG: "",
NEXT_PUBLIC_NETWORK_ICON: "http://blockscout-rpc-adaptor:8888/images/light_icon.png",
NEXT_PUBLIC_NETWORK_ID: "3109",
NEXT_PUBLIC_API_PROTOCOL: "https",
NEXT_PUBLIC_NETWORK_LOGO: "http://blockscout-rpc-adaptor:8888/images/icon.svg",
NEXT_PUBLIC_NETWORK_NAME: "SatoshiVM Alpha Mainnet",
NEXT_PUBLIC_NETWORK_RPC_URL: "https://alpha-rpc-node-http.svmscan.io",
NEXT_PUBLIC_NETWORK_GOVERNANCE_TOKEN_SYMBOL: "BTC",
NEXT_PUBLIC_IS_TESTNET: "false",
NEXT_PUBLIC_OG_IMAGE_URL: "https://satoshivm.io/icon.png",
NEXT_PUBLIC_NETWORK_SHORT_NAME: "SVM Alpha Mainnet",
NEXT_PUBLIC_HOMEPAGE_PLATE_BACKGROUND: "radial-gradient(103.03% 103.03% at 0% 0%, rgba(255, 153, 0, 0.8) 0%, rgba(255, 120, 0, 0.8) 100%), var(--chakra-colors-orange-400)",
}
